package arrange;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

/**
 * Package: arrange
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 10.04.2018 2018
 */
public class NavigateSite {
    public static WebDriver navigateTo(WebDriver webDriver, String url) {
        webDriver.navigate().to(url);
        return webDriver;
    }

    public static WebDriver navigateBack(WebDriver webDriver) {
        webDriver.navigate().back();
        return webDriver;
    }
}
