package arrange;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

/**
 * Package: arrange
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 09.04.2018 2018
 */
public class OpenCloseSite {
    static WebDriver webDriver;
    public static WebDriver openSite(String url){
        webDriver = new ChromeDriver();
        webDriver.manage().window().maximize();;
        webDriver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        webDriver.get(url);
        return webDriver;
    }
    public static void closeSite(WebDriver webDriver) throws InterruptedException {
        Thread.sleep(2000);
        webDriver.close();
    }
}
