package assertion;

import arrange.OpenCloseSite;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;

import java.util.List;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 10.04.2018 2018
 */
public class BaseTest {
    WebDriver webDriver;
    public WebDriverWait wait;
    List<WebElement> webElementList;

    @BeforeMethod (alwaysRun = true)
    public void setUp() throws InterruptedException {
        webDriver = OpenCloseSite.openSite("https://www.wikipedia.org/");
        wait = new WebDriverWait(webDriver,5);
        Thread.sleep(1000);
    }

    @AfterMethod(alwaysRun = true)
    public void tearDown() throws InterruptedException {
        Thread.sleep(1000);
        webDriver.quit();
    }
}
