package assertion;

import arrange.OpenCloseSite;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import static org.testng.Assert.*;

import java.util.Set;
import java.util.concurrent.TimeUnit;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 11.04.2018 2018
 */
public class changeSiteTest {
    WebDriver webDriver;
    @BeforeTest
    public void setUp()throws InterruptedException {
        webDriver = OpenCloseSite.openSite("https://www.anecon.com");
        webDriver.manage().timeouts().implicitlyWait(5,TimeUnit.SECONDS);

    }
    @Test
    public void ChageSiteTest() throws InterruptedException {
        String mainSite = webDriver.getWindowHandle();
        webDriver.findElement(By.xpath("/html/body/footer/div/div/div[2]/div/div[2]/div[1]/a/div")).click();
        Set<String> sites = webDriver.getWindowHandles();
        for(String site : sites){
            if(!mainSite.equals(site)){
                webDriver.switchTo().window(site);
                assertTrue("ANECON Blog".equals(webDriver.findElement(By.id("logo")).getAttribute("title")));
                Thread.sleep(1000);
            } break;
        }

    }
    @AfterMethod
    public void tearDown() throws InterruptedException {
        Thread.sleep(1000);
        webDriver.quit();
    }
}
