package assertion;

import arrange.DataProviderUtil;
import org.openqa.selenium.By;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 11.04.2018 2018
 */
public class DataProviderMassTest extends BaseTest {
    @Test(dataProvider = "languageData", dataProviderClass = DataProviderUtil.class)
    public void languageDifferTest(String xpath, String logoText) throws InterruptedException {
        webDriver.findElement(By.xpath(xpath)).click();
        Thread.sleep(1000);
        assertTrue(logoText.equals(webDriver.findElement(By.xpath("//*[@id='p-logo']/a")).getAttribute("title")));
        webDriver.navigate().back();
    }

}