package assertion;

import org.testng.annotations.Test;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 11.04.2018 2018
 */
public class Main {
    public static void main(String args[]){

    }
}
