package assertion;

import arrange.NavigateSite;
import arrange.OpenCloseSite;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 10.04.2018 2018
 */
public class NavigateSiteTest {
    WebDriver webDriver;

    @BeforeMethod
    public void setUp() throws InterruptedException {
        webDriver = OpenCloseSite.openSite("https://www.wikipedia.org/");
        Thread.sleep(1000);
    }

    @Test
    public void testNavigateTo() {
        webDriver = NavigateSite.navigateTo(webDriver, "https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna");
        assertTrue("https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna".equals(webDriver.getCurrentUrl()));
    }

    @Test
    public void testNavigateBack() {
        webDriver = NavigateSite.navigateTo(webDriver, "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite");
        webDriver.navigate().back();
        assertTrue("Wikipedia".equals(webDriver.getTitle()));
    }


    @AfterMethod
    public void tearDown() throws InterruptedException {
        Thread.sleep(1000);
        webDriver.close();
    }
}