package assertion;

import arrange.NavigateSite;

import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 10.04.2018 2018
 */
public class NavigateSiteTest extends BaseTest {


    @Test(priority = 1,groups = "G1")
    public void testNavigateTo() {
        webDriver = NavigateSite.navigateTo(webDriver, "https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna");
        assertTrue("https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna".equals(webDriver.getCurrentUrl()));
    }

    @Test(priority = 2, groups = "G1")
    public void testNavigateBack() {
        webDriver = NavigateSite.navigateTo(webDriver, "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite");
        webDriver.navigate().back();
        assertTrue("Wikipedia".equals(webDriver.getTitle()));
        webDriver.navigate().forward();
        webDriver.navigate().back();
        webDriver.navigate().refresh();
        assertTrue("Wikipedia".equals(webDriver.getTitle()));

    }


}