package assertion;

import action.OperationOnSite;
import arrange.OpenCloseSite;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.List;

import static org.testng.Assert.*;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 09.04.2018 2018
 */
public class OperationOnSiteTest {
    WebDriver webDriver;
    List<WebElement> webElementList;

    @BeforeMethod
    public void setUp() {
        webDriver = OpenCloseSite.openSite("https://www.wikipedia.org/");
    }

    @Test
    public void testGetWebElementListById() {
        OperationOnSite operationOnSite = new OperationOnSite(webDriver);
        webElementList = operationOnSite.getWebElementList("//a[contains(@href, \"wikipedia.org\")][@class='link-box']");
    }

    @AfterMethod
    public void tearDown() throws InterruptedException {
        OpenCloseSite.closeSite(webDriver);

    }


}