package assertion;

import arrange.OpenCloseSite;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 10.04.2018 2018
 */
public class WikiTestSuite {
    public static WebDriver webDriver;
    public String url;

    @BeforeSuite
    public void setUp() {
        if(webDriver==null){
            webDriver = OpenCloseSite.openSite("https://www.wikipedia.org/");
        }

    }
    @Test
    public void test(){

    }
    @AfterSuite
    public void tearDown() throws InterruptedException {
        OpenCloseSite.closeSite(webDriver);
    }
}
