package action;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import static java.util.logging.Logger.GLOBAL_LOGGER_NAME;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 09.04.2018 2018
 */
public class OperationOnSite {
    WebDriver webDriver;
    List<WebElement> webElementList;
    Logger LOGGER = Logger.getLogger("");


    public OperationOnSite(WebDriver webDriver) {
        this.webDriver = webDriver;

    }

    public WebElement getWebElementById(String xpath) {
        return webDriver.findElement(By.xpath(xpath));
    }

    public List<WebElement> getWebElementList(String xpath) {
        webElementList = webDriver.findElements(By.xpath(xpath));
        printParameter();
        return webElementList;
    }

    public void printParameter() {
        for (WebElement element : webElementList) {
            LOGGER.setLevel(Level.FINE);
            LOGGER.info("Title: " + element.getAttribute("title")+", href: "+element.getAttribute("href"));

        }

    }
}
