package action;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 09.04.2018 2018
 */
public class OperationOnSite {
    WebDriver webDriver;

    public OperationOnSite(WebDriver webDriver) {
        this.webDriver = webDriver;
    }

    public WebElement getWebElementById(String id) {
        return webDriver.findElement(By.id(id));
    }
}
