package action;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 09.04.2018 2018
 */
public class OperationOnSite {
    WebDriver webDriver;
    List<WebElement> webElementList;
    WebElement webElement;
    Logger LOGGER = Logger.getLogger("");


    public OperationOnSite(WebDriver webDriver) {
        this.webDriver = webDriver;

    }

    public WebElement getWebElementById(String id) {

        return webDriver.findElement(By.id(id));
    }

    public void webElementClick(String xpath) {

        webDriver.findElement(By.xpath(xpath)).click();
    }

    public List<WebElement> getWebElementList(String xpath) {
        webElementList = webDriver.findElements(By.xpath(xpath));
        printParameter();
        return webElementList;
    }
    public WebElement getWebElementByXpath(String xpath){
        return webDriver.findElement(By.xpath(xpath));
    }

    public void setWebElementSendKey(WebElement webElement, String value){
        webElement.sendKeys(value);
    }

    public void printParameter() {
        for (WebElement element : webElementList) {
            LOGGER.setLevel(Level.FINE);
            LOGGER.info("Title: " + element.getAttribute("title") + ", href: " + element.getAttribute("href"));

        }

    }
}
